// <auto-generated />
namespace Flights.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_walidations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_walidations));
        
        string IMigrationMetadata.Id
        {
            get { return "201601061824367_delete_walidations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
