// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod3 - Use 'RecordedMethod3Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WinWindow uIHomePageMyFlightsAppWindow1 = this.UIHomePageMyFlightsAppWindow.UIHomePageMyFlightsAppWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UIHomePageMyFlightsAppWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(601, 410));

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(1007, 344));

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(153, 318));

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(363, 302));

            // Type '3' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod3Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(330, 361));
        }
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinWindow uIHomePageMyFlightsAppWindow1 = this.UIHomePageMyFlightsAppWindow.UIHomePageMyFlightsAppWindow1;
            #endregion

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(597, 414));

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(986, 322));

            // Click 'Home Page - My Flights Application' window
            Mouse.Click(uIHomePageMyFlightsAppWindow1, new Point(121, 312));
        }
        
        /// <summary>
        /// login - Use 'loginParams' to pass parameters into this method.
        /// </summary>
        public void login()
        {
            #region Variable Declarations
            WinWindow uILoginMyFlightsApplicWindow1 = this.UILoginMyFlightsApplicWindow.UILoginMyFlightsApplicWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UILoginMyFlightsApplicWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion


            var link = new HtmlHyperlink(uILoginMyFlightsApplicWindow1);
            link.SearchProperties.Add(HtmlHyperlink.PropertyNames.Href, "/Account/Login");
            // Click 'Log in - My Flights Application' window
           Mouse.Click(link);

            // Type 'prezes}@prezes.pl' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.loginParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Log in - My Flights Application' window
            Mouse.Click(uILoginMyFlightsApplicWindow1, new Point(416, 319));

            // Type '12345678' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.loginParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Log in - My Flights Application' window
            Mouse.Click(uILoginMyFlightsApplicWindow1, new Point(274, 403));
        }
        
        #region Properties
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public virtual loginParams loginParams
        {
            get
            {
                if ((this.mloginParams == null))
                {
                    this.mloginParams = new loginParams();
                }
                return this.mloginParams;
            }
        }
        
        public UIHomePageMyFlightsAppWindow UIHomePageMyFlightsAppWindow
        {
            get
            {
                if ((this.mUIHomePageMyFlightsAppWindow == null))
                {
                    this.mUIHomePageMyFlightsAppWindow = new UIHomePageMyFlightsAppWindow();
                }
                return this.mUIHomePageMyFlightsAppWindow;
            }
        }
        
        public UILoginMyFlightsApplicWindow UILoginMyFlightsApplicWindow
        {
            get
            {
                if ((this.mUILoginMyFlightsApplicWindow == null))
                {
                    this.mUILoginMyFlightsApplicWindow = new UILoginMyFlightsApplicWindow();
                }
                return this.mUILoginMyFlightsApplicWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private loginParams mloginParams;
        
        private UIHomePageMyFlightsAppWindow mUIHomePageMyFlightsAppWindow;
        
        private UILoginMyFlightsApplicWindow mUILoginMyFlightsApplicWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// Type '3' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "3";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class loginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'prezes@prezes.pl' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "prezes@prezes.pl";
        
        /// <summary>
        /// Type '12345678' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "12345678";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageMyFlightsAppWindow : WinWindow
    {
        
        public UIHomePageMyFlightsAppWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - My Flights Application";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Home Page - My Flights Application");
            this.WindowTitles.Add("- My Flights Application");
            #endregion
        }
        
        #region Properties
        public WinWindow UIHomePageMyFlightsAppWindow1
        {
            get
            {
                if ((this.mUIHomePageMyFlightsAppWindow1 == null))
                {
                    this.mUIHomePageMyFlightsAppWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIHomePageMyFlightsAppWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - My Flights Application";
                    this.mUIHomePageMyFlightsAppWindow1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIHomePageMyFlightsAppWindow1.WindowTitles.Add("Home Page - My Flights Application");
                    this.mUIHomePageMyFlightsAppWindow1.WindowTitles.Add("- My Flights Application");
                    #endregion
                }
                return this.mUIHomePageMyFlightsAppWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIHomePageMyFlightsAppWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "201749776";
            this.WindowTitles.Add("- My Flights Application");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("- My Flights Application");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginMyFlightsApplicWindow : WinWindow
    {
        
        public UILoginMyFlightsApplicWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Log in";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Log in - My Flights Application");
            #endregion
        }
        
        #region Properties
        public WinWindow UILoginMyFlightsApplicWindow1
        {
            get
            {
                if ((this.mUILoginMyFlightsApplicWindow1 == null))
                {
                    this.mUILoginMyFlightsApplicWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUILoginMyFlightsApplicWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Log in";
                    this.mUILoginMyFlightsApplicWindow1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUILoginMyFlightsApplicWindow1.WindowTitles.Add("Log in - My Flights Application");
                    #endregion
                }
                return this.mUILoginMyFlightsApplicWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUILoginMyFlightsApplicWindow1;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "201749776";
            this.WindowTitles.Add("Log in - My Flights Application");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Log in - My Flights Application");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
